import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import RestaurantCarousel from "../components/RestaurantCarousel/RestaurantCarousel";
import FilterButtonRow from "../components/HomeFilters/FilterButtonRow";

const RestaurantCarouselSection = styled.section`
    width: 100%;
    padding: 0 320px;
`;

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <FilterButtonRow />
                <RestaurantCarouselSection>
                    <RestaurantCarousel />
                </RestaurantCarouselSection>
            </main>
        </>
    );
}
